name: anti_scam_ai
description: A lightweight anti-scam SMS detection app.
version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  google_sign_in: ^6.2.1
  google_sign_in_android: ^6.2.1
  google_sign_in_ios: ^5.9.0
  google_sign_in_platform_interface: ^2.5.0
  google_sign_in_web: ^0.12.4+4

  # Anti-Scam Core
  telephony:
    path: packages/Telephony
  awesome_notifications: ^0.10.1
  shared_preferences: ^2.3.2
  google_fonts: ^6.3.0
  permission_handler: ^11.3.1
  url_launcher: ^6.3.0

  # ✅ Firebase ชุดเดียวกัน (core 2.x + auth/firestore 4.x ล่าสุดของสายนี้)
  firebase_core: ^2.32.0
  firebase_auth: ^4.17.5
  cloud_firestore: ^4.17.5
  dcm: ^1.0.0
  lucide_icons: ^0.257.0
  pie_chart: ^5.0.3
  http: ^1.2.0
  # Local Database
  sqflite: ^2.3.3+1
  path: ^1.9.0
  crypto: ^3.0.6
  # Network and UI
  flutter_svg: ^2.0.9
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  test: ^1.25.15
  flutter_launcher_icons: ^0.14.4


# ❌ เอา dependency_overrides ออก เพื่อไม่ให้บังคับเวอร์ชันแล้วดึงปลั๊กอินผิดเจน
# dependency_overrides:
#   http: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/app_icon.jpg
    - assets/google_icon.png
    - assets/models/sms_spam_model.tflite
    - assets/models/tokenizer.json

flutter_icons:
  android: true
  ios: true
  image_path: "assets/images/app_icon.jpg"
