// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCo6Bu5LAxxN1c_RqsrWQz7sa-GKzGHQk8',
    appId: '1:724135108704:web:446fd57947a1785809a305',
    messagingSenderId: '724135108704',
    projectId: 'project-96e9d',
    authDomain: 'project-96e9d.firebaseapp.com',
    storageBucket: 'project-96e9d.firebasestorage.app',
    measurementId: 'G-PP54Z2N0L6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB05Y6W5iq2e8sg4lF_exMJu3G1enULoXw',
    appId: '1:724135108704:android:ddfc02fe950bb55409a305',
    messagingSenderId: '724135108704',
    projectId: 'project-96e9d',
    storageBucket: 'project-96e9d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCno37ZI2-t74OLiTUbNB4ZS4_gl1L7ryw',
    appId: '1:724135108704:ios:a82ef2046ef2782409a305',
    messagingSenderId: '724135108704',
    projectId: 'project-96e9d',
    storageBucket: 'project-96e9d.firebasestorage.app',
    iosBundleId: 'com.example.antiScamAi',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCno37ZI2-t74OLiTUbNB4ZS4_gl1L7ryw',
    appId: '1:724135108704:ios:a82ef2046ef2782409a305',
    messagingSenderId: '724135108704',
    projectId: 'project-96e9d',
    storageBucket: 'project-96e9d.firebasestorage.app',
    iosBundleId: 'com.example.antiScamAi',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCo6Bu5LAxxN1c_RqsrWQz7sa-GKzGHQk8',
    appId: '1:724135108704:web:614cfa7ff0596c8409a305',
    messagingSenderId: '724135108704',
    projectId: 'project-96e9d',
    authDomain: 'project-96e9d.firebaseapp.com',
    storageBucket: 'project-96e9d.firebasestorage.app',
    measurementId: 'G-8573M77B8V',
  );
}
